# Generated by Django 4.2 on 2023-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                ("id_proveedor", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_proveedor", models.CharField(max_length=100)),
                ("direccion_proveedor", models.CharField(max_length=200)),
                ("codigo_postal_proveedor", models.CharField(max_length=10)),
                ("localidad_proveedor", models.CharField(max_length=100)),
                ("pais_proveedor", models.CharField(max_length=100)),
                ("telefono_proveedor", models.IntegerField()),
                ("correo_proveedor", models.EmailField(max_length=254)),
                ("area_proveedor", models.CharField(max_length=100)),
                ("observaciones_proveedor", models.TextField()),
            ],
            options={"db_table": "proveedor",},
        ),
    ]
