# Generated by Django 4.2 on 2023-07-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedor", "0002_alter_proveedor_area_proveedor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="observaciones_proveedor",
            field=models.TextField(blank=True, null=True),
        ),
    ]
