# Generated by Django 4.2 on 2023-06-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oportunidad", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                ("id_cotizacion", models.AutoField(primary_key=True, serialize=False)),
                ("id_incoterm", models.IntegerField()),
                ("tipo_operacion", models.CharField(max_length=200)),
                ("fecha_cotizacion", models.DateField()),
                ("moneda", models.CharField(max_length=50)),
                ("tipo_cambio", models.CharField(max_length=50)),
                ("plazo_entrega", models.DateField()),
                (
                    "id_oportunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oportunidad.oportunidad",
                    ),
                ),
            ],
            options={"db_table": "cotizacion",},
        ),
    ]
