# Generated by Django 4.2 on 2023-07-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cotizacion", name="id_incoterm",),
        migrations.AddField(
            model_name="cotizacion",
            name="incoterm",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
