# Generated by Django 4.2 on 2023-07-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizacion", "0002_remove_cotizacion_id_incoterm_cotizacion_incoterm"),
    ]

    operations = [
        migrations.RemoveField(model_name="cotizacion", name="incoterm",),
        migrations.AddField(
            model_name="cotizacion",
            name="id_incoterm",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
