# Generated by Django 4.2 on 2023-07-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizacion", "0004_remove_cotizacion_id_incoterm_cotizacion_incoterm"),
    ]

    operations = [
        migrations.RemoveField(model_name="cotizacion", name="fecha_cotizacion",),
        migrations.AlterField(
            model_name="cotizacion",
            name="incoterm",
            field=models.CharField(
                choices=[
                    ("EXW", "EXW"),
                    ("FOB", "FOB"),
                    ("DAP", "DAP"),
                    ("DAT", "DAT"),
                    ("CIP", "CIP"),
                    ("CIF", "CIF"),
                    ("FCA", "FCA"),
                    ("CPT", "CPT"),
                ],
                default="",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="moneda",
            field=models.CharField(
                choices=[
                    ("EURO", "EURO"),
                    ("DOLAR", "DOLAR"),
                    ("PESO ARGENTINO", "PESO ARGENTINO"),
                    ("PESO COLOMBIANO", "PESO COLOMBIANO"),
                    ("PESO CHILENO", "PESO CHILENO"),
                    ("SOL PERUANO", "SOL PERUANO"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tipo_operacion",
            field=models.CharField(
                choices=[("EXW", "EXW"), ("NAC", "NAC"), ("SERV", "SERV")],
                max_length=200,
            ),
        ),
    ]
