# Generated by Django 4.2 on 2023-06-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_cliente", models.CharField(max_length=100)),
                ("direccion_cliente", models.CharField(max_length=200)),
                ("codigo_postal_cliente", models.CharField(max_length=10)),
                ("localidad_cliente", models.CharField(max_length=100)),
                ("pais_cliente", models.CharField(max_length=100)),
                ("telefono_cliente", models.IntegerField()),
                ("correo_cliente", models.EmailField(max_length=254)),
                ("area_cliente", models.CharField(max_length=100)),
                ("observaciones_cliente", models.TextField()),
            ],
            options={"db_table": "cliente",},
        ),
    ]
