# Generated by Django 4.2 on 2023-07-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="pais_cliente",
            field=models.CharField(
                choices=[
                    ("AR", "Argentina"),
                    ("BR", "Brasil"),
                    ("CL", "Chile"),
                    ("CO", "Colombia"),
                    ("MX", "México"),
                    ("PE", "Perú"),
                ],
                max_length=100,
            ),
        ),
    ]
