# Generated by Django 4.2 on 2023-06-20 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('n_orden_compra', models.IntegerField()),
                ('fecha_orden_compra', models.DateField()),
                ('moneda', models.IntegerField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('fecha_entrega_oc', models.DateField()),
                ('fecha_facturacion', models.DateField()),
                ('utilidad_esperada', models.IntegerField()),
                ('observaciones', models.CharField(max_length=100)),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizacion')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
