# Generated by Django 4.2 on 2023-07-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proveedor", "0002_alter_proveedor_area_proveedor_and_more"),
        ("cliente", "0004_alter_cliente_area_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oportunidad",
            fields=[
                ("id_oportunidad", models.AutoField(primary_key=True, serialize=False)),
                ("id_gestion_comercial", models.IntegerField()),
                ("nombre_contacto", models.CharField(default="", max_length=100)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("agua", "Agua"),
                            ("mineria", "Minería"),
                            ("azucar", "Azúcar"),
                            ("gas", "Gas"),
                            ("Oil & gas UP", "Oil & Gas UP"),
                            ("Oil & gas DP", "Oil & Gas DP"),
                            ("eolica", "Eólica"),
                            ("solar", "Solar"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("alcance", models.CharField(max_length=200)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("monto_probable", models.IntegerField()),
                ("fecha_facturacion", models.DateField()),
                (
                    "probabilidad_a_oc",
                    models.IntegerField(
                        choices=[
                            (10, "10"),
                            (25, "25"),
                            (50, "50"),
                            (75, "75"),
                            (90, "90"),
                        ]
                    ),
                ),
                ("observaciones", models.CharField(max_length=100)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.cliente",
                    ),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proveedor.proveedor",
                    ),
                ),
            ],
            options={"db_table": "oportunidad",},
        ),
    ]
