# Generated by Django 4.2 on 2023-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id_oportunidad', models.AutoField(db_column='id_oportunidad', primary_key=True, serialize=False)),
                ('id_gestion_comercial', models.IntegerField(db_column='id_gestion_comercial')),
                ('id_cliente', models.IntegerField(db_column='id_cliente')),
                ('id_contacto', models.IntegerField(db_column='id_contacto')),
                ('id_proveedor', models.IntegerField(db_column='id_proveedor')),
                ('id_area', models.IntegerField(db_column='id_area')),
                ('alcance', models.CharField(db_column='alcance', max_length=200)),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_termino', models.DateField(db_column='fecha_termino')),
                ('monto_probable', models.IntegerField(db_column='monto_probable')),
                ('fecha_facturacion', models.DateField(db_column='fecha_facturacion')),
                ('probabilidad_a_oc', models.IntegerField(db_column='probabilidad_a_oc')),
                ('observaciones', models.CharField(db_column='observaciones', max_length=100)),
            ],
            options={
                'db_table': 'oportunidad',
            },
        ),
    ]
