# Generated by Django 4.2 on 2023-07-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oportunidad", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="oportunidad", name="id_area",),
        migrations.RemoveField(model_name="oportunidad", name="id_cliente",),
        migrations.RemoveField(model_name="oportunidad", name="id_contacto",),
        migrations.RemoveField(model_name="oportunidad", name="id_proveedor",),
        migrations.AddField(
            model_name="oportunidad",
            name="area",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="oportunidad",
            name="nombre_cliente",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="oportunidad",
            name="nombre_contacto",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="oportunidad",
            name="nombre_proveedor",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="alcance",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="fecha_facturacion",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="oportunidad", name="fecha_inicio", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="oportunidad", name="fecha_termino", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="id_gestion_comercial",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="id_oportunidad",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="monto_probable",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="observaciones",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="oportunidad",
            name="probabilidad_a_oc",
            field=models.IntegerField(),
        ),
    ]
