# Generated by Django 4.2 on 2023-07-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oportunidad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oportunidad",
            name="observaciones",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
