# Generated by Django 4.2 on 2023-07-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oportunidad", "0003_alter_oportunidad_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oportunidad",
            name="probabilidad_a_oc",
            field=models.IntegerField(
                choices=[(10, "10"), (25, "25"), (50, "50"), (75, "75"), (90, "90")]
            ),
        ),
    ]
