# Generated by Django 4.2 on 2023-07-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_area_cliente'),
        ('oportunidad', '0003_alter_oportunidad_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
