# Generated by Django 4.2 on 2023-07-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('oportunidad', '0004_oportunidad_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidad',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='oportunidad',
            name='nombre_proveedor',
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
